# This file is used to install the Foundry toolchain and verify the installation.

- name: Install Foundry
  uses: foundry-rs/foundry-toolchain@v1

- name: Verify Forge installation
  run: forge --version

- name: Install Solidity Dependencies
  run: forge soldeer update -d

- name: install protobuf and gmp
  run: |
    sudo apt-get update
    sudo apt-get install -y protobuf-compiler libprotobuf-dev libgmp-dev

- name: Install LLVM and Clang
  uses: KyleMayes/install-llvm-action@v2
  with:
    version: "19.1.7"
